services:
  unitystation-wiki:
    build: .
    restart: always
    networks:
      - default
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unitystation-wiki.rule=Host(`unitystation-wiki.unionrolistes.fr`)"
      - "traefik.http.routers.unitystation-wiki.entrypoints=websecure"
      - "traefik.http.routers.unitystation-wiki.tls.certresolver=le"
      - "traefik.http.services.unitystation-wiki.loadbalancer.server.port=3000"

networks:
  traefik-public:
    external: true